### ISSUE TITLE
feat: Support generating fake data with future SDK version

### ISSUE THREAD

**Issue by ReubenFrankel** [MeltanoLabs/meltano-map-transform#215]
Now https://github.com/meltano/sdk/pull/2170 has been merged and once the next version of the SDK is released, it would be great to bump the `singer-sdk` version used here with the `faker` extra to leverage the new feature.

**Comment by edgarrmondragon** [comment]
@ReubenFrankel would you expect this package to enable the use of `faker` by default, i.e. depend directly on `singer-sdk[faker]`, or would you prefer it to have its own extra?

I think I prefer on the former, since that makes this package more useful and it's presumably installed only once per project, unlike extractors.

**Comment by ReubenFrankel** [comment]
@edgarrmondragon Yep, I think by default is the most useful.

**Comment by ReubenFrankel** [comment]
@edgarrmondragon Yep, I think by default is the most useful.

**Comment by ReubenFrankel** [comment]
@maxmarcon Looks like that got added recently and will be included in the next SDK release. This plugin (and any other built with the SDK) will need to upgrade to the new version before what you are trying will work.

https://github.com/meltano/sdk/commit/1333278007c8e4daf03f82049de102f041bda878

In the meantime, if you want to set a static seed, you can do this through `faker_config.seed` as in the docs example you linked, or in an expression with

```
   - name: meltano-map-transformer
      config:
          stream_maps:
              data_platform_raw-tbii_daily_gmv_nmv:
                  tb_channel_id: fake.seed_instance(0) and fake.pyint()
```
