### ISSUE TITLE
Renaming a column

### ISSUE THREAD

**Issue by miko866** [MeltanoLabs/meltano-map-transform#252]
Hi,
I need to rename column index to [index] in MSSQL because it is a keyword.
Unfortunately I didn’t find a example or syntax how this would be possible.
Could someone help me?

**Comment by edgarrmondragon** [comment]
Hi @miko866, you could try something like

```yaml
stream_maps:
  # Apply these transforms to the stream called 'customers'
  my_stream:
    # drop the original field
    index: __NULL__
    # alias
    index_field: index
```
