### ISSUE TITLE
Faker not defined

### ISSUE THREAD

**Issue by maxmarcon** [MeltanoLabs/meltano-map-transform#291]
Hi! I wanted to use the  `stream_maps` API (with faker) with [tap-postgres](https://hub.meltano.com/extractors/tap-postgres/). However, apparently, tap-postgres doesn't support faker (I get an error saying that the "fake object is not defined").

As a workaround, I'm using meltano-map-transform instead. fake is defined, however when I want to set the seed following [this example](https://sdk.meltano.com/en/latest/stream_maps.html#masking-data-with-faker) from the Meltano SDK docs:

```
   - name: meltano-map-transformer
      config:
         stream_maps:
              data_platform_raw-tbii_daily_gmv_nmv:
                  tb_channel_id: Faker.seed(0) or fake.pyint()
         faker_config:
            seed: 0
```

I get an error:

```
'Faker' is not defined for expression 'Faker.seed(0) or fake.pyint()'
```

Do you know why? Thanks

I'm using:
meltano-map-transform: https://github.com/MeltanoLabs/meltano-map-transform.git@v0.7.1
meltano: 3.4.1
python: 3.9.18
