### ISSUE TITLE
Invalid schema when modifying an existing property in place

### ISSUE THREAD

**Issue by pnadolny13** [MeltanoLabs/meltano-map-transform#30]
This could be user error in that I shouldnt be modifying an existing key in place but I noticed that when I use the mapper plugins to use stream maps and I overwrite a stream property it causes a target failure on schema validation. If I change the name of the new property in my mapper and null out the original I have no issue (thats what I ended up doing) but wanted to flag this.

```yaml
plugins:
  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
    mappings:
    - name: my_mapping_name
      config:
        stream_maps:
          my_stream_name:
            existing_col: "record.get('existing_col', '')"
```

This ends up sending a schema that looks like the following, which I think is invalid. The error is `unhashable type: 'list'`.

```
{'properties': {'existing_col': {'type': [['null', 'string'], 'null']} ...
```

Its like we're manipulating the schema record and appending to the type list vs overwriting. Or maybe we do want to append for some reason but its not doing it properly.
